# Generated by Django 2.1.7 on 2019-06-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('num', models.CharField(max_length=255, unique=True)),
                ('question', models.TextField(max_length=500)),
                ('opt_a', models.CharField(max_length=255)),
                ('opt_b', models.CharField(max_length=255)),
                ('opt_c', models.CharField(max_length=255)),
                ('opt_d', models.CharField(max_length=255)),
                ('hint', models.TextField(max_length=500)),
                ('answer', models.TextField(max_length=1)),
                ('right_count', models.PositiveIntegerField()),
                ('wrong_count', models.PositiveIntegerField()),
                ('total_right_count', models.PositiveIntegerField()),
                ('total_wrong_count', models.PositiveIntegerField()),
            ],
        ),
    ]
