# Generated by Django 2.1.7 on 2019-06-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='last_answered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='num',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
