# Generated by Django 2.1.7 on 2019-06-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20190616_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
