# Generated by Django 2.1.7 on 2019-06-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20190617_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='identifier',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
