# Generated by Django 2.1.7 on 2019-06-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_info_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='question',
            name='num',
        ),
    ]
