# Generated by Django 2.2.2 on 2019-07-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_question_question_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Excel', 'Excel'), ('Word', 'Word'), ('Powerpoint', 'Powerpoint'), ('Operating System', 'Operating System'), ('Computer Fundamental', 'Computer Fundamental')], default='Uncategorized', max_length=20),
        ),
    ]
