# Generated by Django 2.2.2 on 2019-07-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='iteration_num_computer_fundamental',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='info',
            name='iteration_num_excel',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='info',
            name='iteration_num_operating_system',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='info',
            name='iteration_num_powerpoint',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='info',
            name='iteration_num_uncategorized',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='info',
            name='iteration_num_word',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='info',
            name='last_answered_computer_fundamental',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='last_answered_excel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='last_answered_operating_system',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='last_answered_powerpoint',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='last_answered_uncategorized',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='last_answered_word',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='total_questions_computer_fundamental',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='total_questions_excel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='total_questions_operating_system',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='total_questions_powerpoint',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='total_questions_uncategorized',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='total_questions_word',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
