# Generated by Django 2.2.2 on 2019-07-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20190716_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='categories',
            new_name='category',
        ),
    ]
