# Generated by Django 2.2.2 on 2019-07-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20190716_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='iteration_num',
        ),
        migrations.RemoveField(
            model_name='info',
            name='iteration_num_computer_fundamental',
        ),
        migrations.RemoveField(
            model_name='info',
            name='iteration_num_excel',
        ),
        migrations.RemoveField(
            model_name='info',
            name='iteration_num_operating_system',
        ),
        migrations.RemoveField(
            model_name='info',
            name='iteration_num_powerpoint',
        ),
        migrations.RemoveField(
            model_name='info',
            name='iteration_num_uncategorized',
        ),
        migrations.RemoveField(
            model_name='info',
            name='iteration_num_word',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('uncategorized', 'Uncategorized'), ('excel', 'Excel'), ('word', 'Word'), ('powerpoint', 'Powerpoint'), ('operating-system', 'Operating System'), ('computer-misc', 'Computer Fundamental')], default='Uncategorized', max_length=20),
        ),
    ]
