# Generated by Django 2.2.2 on 2019-07-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20190716_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='last_answered',
        ),
        migrations.RemoveField(
            model_name='info',
            name='last_answered_computer_fundamental',
        ),
        migrations.RemoveField(
            model_name='info',
            name='last_answered_excel',
        ),
        migrations.RemoveField(
            model_name='info',
            name='last_answered_operating_system',
        ),
        migrations.RemoveField(
            model_name='info',
            name='last_answered_powerpoint',
        ),
        migrations.RemoveField(
            model_name='info',
            name='last_answered_uncategorized',
        ),
        migrations.RemoveField(
            model_name='info',
            name='last_answered_word',
        ),
    ]
