# Generated by Django 2.2.2 on 2019-07-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20190717_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='right_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='total_right_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='total_wrong_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='wrong_count',
        ),
    ]
