# Generated by Django 2.2.3 on 2019-07-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20190717_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('uncategorized', 'Uncategorized'), ('excel', 'Excel'), ('word', 'Word'), ('powerpoint', 'Powerpoint'), ('operating_system', 'Operating System'), ('computer_misc', 'Computer Fundamental')], default='Uncategorized', max_length=20),
        ),
    ]
