# Generated by Django 2.2.3 on 2019-07-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20190721_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='opt_e',
            field=models.CharField(blank=True, default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='opt_f',
            field=models.CharField(blank=True, default='null', max_length=255),
        ),
    ]
