# Generated by Django 2.2.3 on 2019-07-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20190721_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='opt_e',
            field=models.CharField(blank=True, default='-null-', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt_f',
            field=models.CharField(blank=True, default='-null-', max_length=255),
        ),
    ]
