# Generated by Django 2.2.3 on 2019-07-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_auto_20190721_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='total_questions_computer_fundamental',
            new_name='total_questions_computer_misc',
        ),
    ]
